HTSD-17 New Resend rules for Reporting Entity
hmrc/cbcr-frontend pull request #480
Opened 2020-11-02 10:28 UTC by rajanimohan22

HTSD-17  New Resend rules for Reporting Entity

New feature

Checklist

 - [x]  I've made every effort to commit high quality, clean code and I have executed relevant static analyses to be sure
 - [x]  I've included appropriate tests with any code I've added (Unit, Integration, Acceptance etc.)
 - [x]  I've added my code using logical, atomic commits, squashing as appropriate - including the JIRA issue number in the commit message
 - [x]  I've run a dependency check to ensure all dependencies are up to date

2020-11-02 14:42 UTC, calinursaciuc commented on app/uk/gov/hmrc/cbcrfrontend/services/CBCBusinessRuleValidator.scala
> +  private def bdskjfbdksjf: Boolean =
to delete this def

2020-11-02 14:44 UTC, calinursaciuc commented on app/uk/gov/hmrc/cbcrfrontend/services/CBCBusinessRuleValidator.scala
> +                   case DocRefIdResponses.Invalid => Left(ResentDataIsUnknownError)
This one should be ResendDocRefIdInvalid instead of Unknown

2020-11-02 14:46 UTC, calinursaciuc commented on conf/messages
> +error.ResendDocRefIdInvalid=Error Code80014 - The DocRefID specified for the Resend option (OECD0) is no longer valid (invalidated or outdated by a previous correction message)
a space after Code

2020-11-02 16:26 UTC, calinursaciuc commented on test/resources/cbcr-valid-nonGBTINInDocRefId.xml
> +            https://catalogue.tax.service.gov.uk/teams/API%20Services
remove this probably unintentional copy/paste

2020-11-02 16:35 UTC, calinursaciuc commented on test/uk/gov/hmrc/cbcrfrontend/services/CBCXMLValidatorSpec.scala
> +      println("MOHAN MOHAN ::: " + validate.errorsCollection)
remove this println

2020-11-02 16:36 UTC, calinursaciuc commented on test/uk/gov/hmrc/cbcrfrontend/services/GuiceConfigSpec.scala
> +    println(">>>>>>" + validator.validateSchema(validXmlFile).errorsCollection)
remove this println

2020-11-02 16:36 UTC, calinursaciuc commented on test/uk/gov/hmrc/cbcrfrontend/services/SubscriptionDataServiceSpec.scala
> +  //implicit lazy val url = new ServiceUrl[CbcrsUrl] { val url = servicesConfig.baseUrl("cbcr") }
remove this comment

2020-11-02 16:37 UTC, calinursaciuc requested changes
See comments

2020-11-02 21:03 UTC, rajanimohan22 commented on app/uk/gov/hmrc/cbcrfrontend/services/CBCBusinessRuleValidator.scala
> +  private def bdskjfbdksjf: Boolean =
Done

2020-11-02 21:03 UTC, rajanimohan22 commented on conf/messages
> +error.ResendDocRefIdInvalid=Error Code80014 - The DocRefID specified for the Resend option (OECD0) is no longer valid (invalidated or outdated by a previous correction message)
Done

2020-11-02 21:03 UTC, rajanimohan22 commented on test/resources/cbcr-valid-nonGBTINInDocRefId.xml
> +            https://catalogue.tax.service.gov.uk/teams/API%20Services
Done

2020-11-02 21:03 UTC, rajanimohan22 commented on test/uk/gov/hmrc/cbcrfrontend/services/CBCXMLValidatorSpec.scala
> +      println("MOHAN MOHAN ::: " + validate.errorsCollection)
Done

2020-11-02 21:03 UTC, rajanimohan22 commented on test/uk/gov/hmrc/cbcrfrontend/services/GuiceConfigSpec.scala
> +    println(">>>>>>" + validator.validateSchema(validXmlFile).errorsCollection)
Done

2020-11-02 21:04 UTC, rajanimohan22 commented on test/uk/gov/hmrc/cbcrfrontend/services/SubscriptionDataServiceSpec.scala
> +  //implicit lazy val url = new ServiceUrl[CbcrsUrl] { val url = servicesConfig.baseUrl("cbcr") }
Done

2020-11-02 21:04 UTC, rajanimohan22 commented on app/uk/gov/hmrc/cbcrfrontend/services/CBCBusinessRuleValidator.scala
> +                   case DocRefIdResponses.Invalid => Left(ResentDataIsUnknownError)
Not sure the exact change you are asking for

2020-11-03 07:49 UTC, calinursaciuc commented on app/uk/gov/hmrc/cbcrfrontend/services/CBCBusinessRuleValidator.scala
> +                   case DocRefIdResponses.Invalid => Left(ResentDataIsUnknownError)
When DocRefIdResponses.Invalid => Left(ResentIsInvalid) instead of ResentDataIsUnknownError

2020-11-03 08:34 UTC, rajanimohan22 commented on app/uk/gov/hmrc/cbcrfrontend/services/CBCBusinessRuleValidator.scala
> +                   case DocRefIdResponses.Invalid => Left(ResentDataIsUnknownError)
Done

2020-11-03 08:40 UTC, calinursaciuc approved these changes

2020-11-03 09:16 UTC, merged