DLS-8062 use google phone number validation library
hmrc/cbcr-frontend pull request #541
Opened 2023-05-30 13:15 UTC by AivarsSmaukstelis

# DLS-8062 

New feature

Changed form validation from custom phone number validation to a google phone validation library

## Checklist

 - [X]  I've made every effort to commit high quality, clean code and I have executed relevant static analyses to be sure
 - [ ]  I've included appropriate tests with any code I've added (Unit, Integration, Acceptance etc.)
 - [X]  I've added my code using logical, atomic commits, squashing as appropriate - including the JIRA issue number in the commit message
 - [x]  I've run a dependency check to ensure all dependencies are up to date

2023-05-30 13:29 UTC, lutnos requested changes

2023-05-30 13:29 UTC, lutnos commented on app/uk/gov/hmrc/cbcrfrontend/form/mappings/CbcrMapping.scala
> +object CbcrMapping {
This is not the same camel case convention used elsewhere. To be consistent with others, at least, it should be `CBCRMapping`, please.

2023-05-30 16:49 UTC, AivarsSmaukstelis commented on app/uk/gov/hmrc/cbcrfrontend/form/mappings/CbcrMapping.scala
> +object CbcrMapping {
thanks, fixed

2023-06-01 07:27 UTC, lutnos approved these changes

2023-07-20 10:29 UTC, closed without merging