DLS-8358 updating to new layout
hmrc/cbcr-frontend pull request #560
Opened 2023-07-14 15:03 UTC by goodvibes

https://jira.tools.tax.service.gov.uk/browse/DLS-8358

2023-07-17 14:37 UTC, ruthdas03 requested changes

2023-07-17 14:37 UTC, ruthdas03 commented on app/uk/gov/hmrc/cbcrfrontend/views/notAuthorisedEnhancement.scala.html
> +  <h1 class="govuk-heading-l">@Messages("notAuthorised.enhancement.heading")</h1>
Can we use implicit `messages` instead of  `Messages`

Also in order to follow the pattern we can make title and page heading the same . Can we please use variable @title for  `notAuthorised.enhancement.title` and use this in heading and title both. By this we can remove`notAuthorised.enhancement.heading`

2023-07-18 15:17 UTC, goodvibes commented on app/uk/gov/hmrc/cbcrfrontend/views/notAuthorisedEnhancement.scala.html
>  @mainTemplate(Messages("notAuthorised.enhancement.title")) {
done

2023-07-18 15:18 UTC, goodvibes commented on app/uk/gov/hmrc/cbcrfrontend/views/notAuthorisedEnhancement.scala.html
> +  <h1 class="govuk-heading-l">@Messages("notAuthorised.enhancement.heading")</h1>
the layout doesn't currently use a gds title style attribute as this would involve updating all pages, which really needs it's own ticket. I've still updated the title to use a variable, so it should just mean replacing the message with the variable when we come to do that.

2023-07-19 10:13 UTC, ruthdas03 approved these changes

2023-07-19 10:14 UTC, merged