DLS-8832 Missing option for finding existing UTR
hmrc/cbcr-frontend pull request #608
Opened 2023-10-10 15:10 UTC by goodvibes

https://jira.tools.tax.service.gov.uk/browse/DLS-8832

2023-10-10 19:02 UTC, Timidigital approved these changes

2023-10-11 08:10 UTC, nubz requested changes

2023-10-11 08:59 UTC, goodvibes commented on conf/messages
> +subscribeFirst.utr.hint=This is 10 numbers, for example 123456789. It will be on tax returns and other letters about Corporation Tax or Self Assessment for a business partnership. It may be called 'r
done

2023-10-11 09:22 UTC, nubz approved these changes

2023-10-11 09:32 UTC, merged