DLS-10863: Update service/ test pack dependencies to the latest versions
hmrc/cbcr-frontend pull request #661
Opened 2024-11-19 14:50 UTC by karolina-zaborska

### **HANDOVER:**

**Helpful links:**

- Our previous PR addressing the same issue for CBCR: https://github.com/hmrc/cbcr/pull/245/files#diff-2c8333f42986702f0da9104f540f6f70497eb4d5e3453b13559e7a6986e3cc39
- Our previous PR addressing the same issue for CBCR-STUBS: https://jira.tools.tax.service.gov.uk/browse/DLS-10865 (divided to two PRs) 

**Make sure that you have:**

- [ ] addressed the BOT suggestion - that requires Java 17 so maybe we need to discuss that with the team
- [ ] run the ATs and they all passed (bear in mind the intermittent failures that we know of)

===========================

Additonal info:

### **| Documentation for the addition of AuthRedirectsExternal file |**

_Background:_

With the upgrade of bootstrap to 8.4.0. the AuthRedirects.scala stopped being a member of the bootstrap.config. Below is a brief piece of the error that I received

object AuthRedirects is not a member of package uk.gov.hmrc.play.bootstrap.config
[error] import uk.gov.hmrc.play.bootstrap.config.AuthRedirects
not found: type AuthRedirects

We have experienced that in the past, see here: https://hmrcdigital.slack.com/archives/C03D5C9F6RX/p1708699179674479

_Solution:_

To address that issue the AuthRedirectsExternal.scala file has been added under [DLS-10863](https://jira.tools.tax.service.gov.uk/browse/DLS-10863). The contents of the file were copied from the old version of the bootstrap library.
See the source: https://github.com/hmrc/bootstrap-play/blob/main/bootstrap-common-play-28/src/main/scala/uk/gov/hmrc/play/bootstrap/config/AuthRedirects.scala

Later on I've added the file test/uk/gov/hmrc/cbcrfrontend/auth/AuthRedirectsExternalSpec.scala with the tests for the content of AuthRedirectsExternal.scala.

The source for the contents implemented in AuthRedirectsExternal.scala. can be found here:
https://github.com/hmrc/bootstrap-play/blob/main/bootstrap-common-play-28/src/test/scala/uk/gov/hmrc/play/bootstrap/config/AuthRedirectsSpec.scala

==========

Note for myself:
https://github.com/hmrc/help-to-save-stride-frontend/pull/226

==============

2024-12-03 17:54 UTC, johno1985 commented
rebuild

2024-12-04 10:41 UTC, vamsikrishnapujari commented
rebuild

2024-12-04 18:41 UTC, ruthdas03 requested changes

2024-12-04 18:41 UTC, ruthdas03 commented on project/AppDependencies.scala
>    val hmrcMongoVersion = "1.4.0"
As per the catalogue this can be upgraded to 2.3.0

2024-12-04 18:41 UTC, ruthdas03 commented on project/AppDependencies.scala
> -  val hmrcBootstrapVersion = "8.3.0"
As per the catalogue this can be upgraded to 9.5.0

2024-12-04 18:41 UTC, ruthdas03 commented on project/AppDependencies.scala
> -    "com.sun.msv.datatype.xsd" % "xsdlib"                           % "2013.2",
Why are we downgrading it from 2013.2 to 20060615

2024-12-05 09:39 UTC, vamsikrishnapujari commented on project/AppDependencies.scala
> -  val hmrcBootstrapVersion = "8.3.0"
The bootstrap version upgrade for CBCR will require a separate story because it requires many changes.
https://jira.tools.tax.service.gov.uk/browse/DLS-11141

2024-12-05 11:38 UTC, hmrc-web-operations commented
Thank you for submitting a pull request on this HMRC repository. A member of the HMRC team will review your changes and action accordingly.

HMRC reviewer: please reference [this runbook](https://github.com/hmrc/build-and-deploy/blob/main/runbooks/reviewing_external_pull_requests.md) for guidance on how to proceed.

2024-12-05 11:40 UTC, vamsikrishnapujari commented
rebuild

2024-12-05 11:40 UTC, vamsikrishnapujari commented on project/AppDependencies.scala
> -    "com.sun.msv.datatype.xsd" % "xsdlib"                           % "2013.2",
Upgraded to latest version

2024-12-05 11:41 UTC, vamsikrishnapujari commented on project/AppDependencies.scala
>    val hmrcMongoVersion = "1.4.0"
Upgraded to latest version

2024-12-05 14:36 UTC, ruthdas03 approved these changes
Couldn't run the ATs successfully locally, approving so that ATs can be run in Jenkins

2024-12-05 15:00 UTC, merged